services:
  app:
    build:
      context: .
      target: app
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
    image: ${APP_IMAGE:-laravel-demo-app}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-false}
    volumes:
      - storage:/var/www/html/storage
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
    networks:
      - laravel

  web:
    build:
      context: .
      target: web
    image: ${WEB_IMAGE:-laravel-demo-web}
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8080}:80"
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:-_}
    depends_on:
      - app
    volumes:
      - storage:/var/www/html/storage:ro
      - ./database/database.sqlite:/var/www/html/database/database.sqlite:ro
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  storage:
