version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      - web

  web:
    image: nginx:1.27-alpine
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
